//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shop.Data.SampleData", typeof(SampleData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;footer-bottom-cate&quot;&gt;
        ///                &lt;h6&gt;CATEGORIES&lt;/h6&gt;
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Curabitur sapien&lt;/a&gt;&lt;/li&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Dignissim purus&lt;/a&gt;&lt;/li&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Tempus pretium&lt;/a&gt;&lt;/li&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Dignissim neque&lt;/a&gt;&lt;/li&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Ornared id aliquet&lt;/a&gt;&lt;/li&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Ultrices id du&lt;/a&gt;&lt;/li&gt;
        ///                    &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Commodo s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;FLAT 50% 0FF&lt;/h2&gt;
        ///								&lt;label&gt;FOR ALL PURCHASE &lt;b&gt;VALUE&lt;/b&gt;&lt;/label&gt;
        ///								&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et &lt;/p&gt;					
        ///								&lt;span class=&quot;on-get&quot;&gt;GET NOW&lt;/span&gt;.
        /// </summary>
        internal static string Slider1Description {
            get {
                return ResourceManager.GetString("Slider1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;FLAT 50% 0FF&lt;/h2&gt;
        ///								&lt;label&gt;FOR ALL PURCHASE &lt;b&gt;VALUE&lt;/b&gt;&lt;/label&gt;
        ///								&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et &lt;/p&gt;					
        ///								&lt;span class=&quot;on-get&quot;&gt;GET NOW&lt;/span&gt;.
        /// </summary>
        internal static string Slider2Description {
            get {
                return ResourceManager.GetString("Slider2Description", resourceCulture);
            }
        }
    }
}
